dist: bionic
sudo: false
language: python
python:
- 3.6
- 3.7
- 3.8
- pypy3
addons:
  apt:
    packages:
      - rustc
      - cargo
install:
- pip install --upgrade pip
- pip install codecov
- pip install isort
- pip install tox
- pip install tox-travis
script:
- codecov --version
- tox
- isort --check src tests
after_success:
- codecov
notifications:
  email: false
